spring:
  application:
    name: kafka-replay
  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API:}
      chat:
        options:
          model: claude-3-5-haiku-latest
logging:
  level:
    org.apache.kafka: WARN